export const MomentaryDataJsx = [
  {
    id: 1,
    img: "http://localhost:3000/images/coin-icon/BTC.png",
    englishName: "Bitcoin",
    PersianName: "بیت کوین",
    tetherPrice: 20072,
    tomanPrice: 937362000,
  },
  {
    id: 2,
    img: "http://localhost:3000/images/coin-icon/ETH.png",
    englishName: "Etherium",
    PersianName: "اتریوم",
    tetherPrice: 20072,
    tomanPrice: 937362000,
  },
  {
    id: 3,
    img: "http://localhost:3000/images/coin-icon/BNB.png",
    englishName: "BNB",
    PersianName: "بایننس کوین",
    tetherPrice: 274,
    tomanPrice: 12734016,
  },
  {
    id: 4,
    img: "http://localhost:3000/images/coin-icon/DOG.png",
    englishName: "DOGE",
    PersianName: "دوج کوین",
    tetherPrice: 0.064,
    tomanPrice: 3009,
  },
  {
    id: 5,
    img: "http://localhost:3000/images/coin-icon/SHIB.png",
    englishName: "SHIBA",
    PersianName: "شیبا",
    tetherPrice: 20072,
    tomanPrice: 937362000,
  },
  {
    id: 6,
    img: "http://localhost:3000/images/coin-icon/Polkadot.PNG",
    englishName: "DOT",
    PersianName: "پولکادات",
    tetherPrice: 5.35,
    tomanPrice: 248239,
  },
  {
    id: 7,
    img: "http://localhost:3000/images/coin-icon/ETC.png",
    englishName: "ETC",
    PersianName: "اتریوم کلاسیک",
    tetherPrice: 16.32,
    tomanPrice: 780000,
  },
  {
    id: 8,
    img: "http://localhost:3000/images/coin-icon/cardano.png",
    englishName: "ADA",
    PersianName: "کاردانو",
    tetherPrice: 0.31,
    tomanPrice: 14384,
  },
];
